[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
#spacetimedb-sdk = "1.0"
spacetimedb-sdk = { version="1.0.1",  path="/home/user/SOURCE/SpacetimeDB/crates/sdk/" }
hex = "0.4"
ctrlc = { version="3.4", features = [ "termination" ] }

