#!/usr/bin/bash

#logout then login again, in case we're using ./run_standalone_temp.sh as the server, which means, we can't use the prev. server's creds on the new server! aka 'TokenError(Error(InvalidSignature))'
#spacetime logout
#export RUST_BACKTRACE=1
set -x
autoslocalscripts="autoslocalscripts"
#^ useless
#This works first time, the fails due to being already added!
spacetime server add \
--cert ../spacetimedb-cert-gen/ca.crt \
--url https://127.1.2.3:6543 \
$autoslocalscripts \

set -e

#spacetime login --server-issued-login https://127.1.2.3:6543 --cert ../spacetimedb-cert-gen/ca.crt
spacetime login --server-issued-login $autoslocalscripts --cert ../spacetimedb-cert-gen/ca.crt

spacetime server list
spacetime publish --yes --server $autoslocalscripts --project-path server quickstart-chat --cert ../spacetimedb-cert-gen/ca.crt
#spacetime publish --project-path server quickstart-chat --cert ../spacetimedb-cert-gen/ca.crt
echo "all good."
